//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace simply_forum
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class small_forumEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new small_forumEntities1 object using the connection string found in the 'small_forumEntities1' section of the application configuration file.
        /// </summary>
        public small_forumEntities1() : base("name=small_forumEntities1", "small_forumEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new small_forumEntities1 object.
        /// </summary>
        public small_forumEntities1(string connectionString) : base(connectionString, "small_forumEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new small_forumEntities1 object.
        /// </summary>
        public small_forumEntities1(EntityConnection connection) : base(connection, "small_forumEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MESSAGES> MESSAGES
        {
            get
            {
                if ((_MESSAGES == null))
                {
                    _MESSAGES = base.CreateObjectSet<MESSAGES>("MESSAGES");
                }
                return _MESSAGES;
            }
        }
        private ObjectSet<MESSAGES> _MESSAGES;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TOPICS> TOPICS
        {
            get
            {
                if ((_TOPICS == null))
                {
                    _TOPICS = base.CreateObjectSet<TOPICS>("TOPICS");
                }
                return _TOPICS;
            }
        }
        private ObjectSet<TOPICS> _TOPICS;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MESSAGES EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMESSAGES(MESSAGES mESSAGES)
        {
            base.AddObject("MESSAGES", mESSAGES);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TOPICS EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTOPICS(TOPICS tOPICS)
        {
            base.AddObject("TOPICS", tOPICS);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="small_forumModel", Name="MESSAGES")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MESSAGES : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MESSAGES object.
        /// </summary>
        /// <param name="mESSAGE_ID">Initial value of the MESSAGE_ID property.</param>
        /// <param name="tEXT">Initial value of the TEXT property.</param>
        /// <param name="aUTHOR">Initial value of the AUTHOR property.</param>
        /// <param name="dATE_CREATE">Initial value of the DATE_CREATE property.</param>
        public static MESSAGES CreateMESSAGES(global::System.Int32 mESSAGE_ID, global::System.String tEXT, global::System.String aUTHOR, global::System.DateTime dATE_CREATE)
        {
            MESSAGES mESSAGES = new MESSAGES();
            mESSAGES.MESSAGE_ID = mESSAGE_ID;
            mESSAGES.TEXT = tEXT;
            mESSAGES.AUTHOR = aUTHOR;
            mESSAGES.DATE_CREATE = dATE_CREATE;
            return mESSAGES;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 MESSAGE_ID
        {
            get
            {
                return _MESSAGE_ID;
            }
            set
            {
                if (_MESSAGE_ID != value)
                {
                    OnMESSAGE_IDChanging(value);
                    ReportPropertyChanging("MESSAGE_ID");
                    _MESSAGE_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MESSAGE_ID");
                    OnMESSAGE_IDChanged();
                }
            }
        }
        private global::System.Int32 _MESSAGE_ID;
        partial void OnMESSAGE_IDChanging(global::System.Int32 value);
        partial void OnMESSAGE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TEXT
        {
            get
            {
                return _TEXT;
            }
            set
            {
                if (_TEXT != value)
                {
                    OnTEXTChanging(value);
                    ReportPropertyChanging("TEXT");
                    _TEXT = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TEXT");
                    OnTEXTChanged();
                }
            }
        }
        private global::System.String _TEXT;
        partial void OnTEXTChanging(global::System.String value);
        partial void OnTEXTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AUTHOR
        {
            get
            {
                return _AUTHOR;
            }
            set
            {
                if (_AUTHOR != value)
                {
                    OnAUTHORChanging(value);
                    ReportPropertyChanging("AUTHOR");
                    _AUTHOR = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("AUTHOR");
                    OnAUTHORChanged();
                }
            }
        }
        private global::System.String _AUTHOR;
        partial void OnAUTHORChanging(global::System.String value);
        partial void OnAUTHORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DATE_CREATE
        {
            get
            {
                return _DATE_CREATE;
            }
            set
            {
                if (_DATE_CREATE != value)
                {
                    OnDATE_CREATEChanging(value);
                    ReportPropertyChanging("DATE_CREATE");
                    _DATE_CREATE = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DATE_CREATE");
                    OnDATE_CREATEChanged();
                }
            }
        }
        private global::System.DateTime _DATE_CREATE;
        partial void OnDATE_CREATEChanging(global::System.DateTime value);
        partial void OnDATE_CREATEChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="small_forumModel", Name="TOPICS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TOPICS : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TOPICS object.
        /// </summary>
        /// <param name="tOPIC_ID">Initial value of the TOPIC_ID property.</param>
        public static TOPICS CreateTOPICS(global::System.Int32 tOPIC_ID)
        {
            TOPICS tOPICS = new TOPICS();
            tOPICS.TOPIC_ID = tOPIC_ID;
            return tOPICS;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TOPIC_ID
        {
            get
            {
                return _TOPIC_ID;
            }
            set
            {
                if (_TOPIC_ID != value)
                {
                    OnTOPIC_IDChanging(value);
                    ReportPropertyChanging("TOPIC_ID");
                    _TOPIC_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TOPIC_ID");
                    OnTOPIC_IDChanged();
                }
            }
        }
        private global::System.Int32 _TOPIC_ID;
        partial void OnTOPIC_IDChanging(global::System.Int32 value);
        partial void OnTOPIC_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AUTHOR
        {
            get
            {
                return _AUTHOR;
            }
            set
            {
                OnAUTHORChanging(value);
                ReportPropertyChanging("AUTHOR");
                _AUTHOR = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AUTHOR");
                OnAUTHORChanged();
            }
        }
        private global::System.String _AUTHOR;
        partial void OnAUTHORChanging(global::System.String value);
        partial void OnAUTHORChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DATE_CREATE
        {
            get
            {
                return _DATE_CREATE;
            }
            set
            {
                OnDATE_CREATEChanging(value);
                ReportPropertyChanging("DATE_CREATE");
                _DATE_CREATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DATE_CREATE");
                OnDATE_CREATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _DATE_CREATE;
        partial void OnDATE_CREATEChanging(Nullable<global::System.DateTime> value);
        partial void OnDATE_CREATEChanged();

        #endregion
    
    }

    #endregion
    
}
